<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Fluent</string>
    <key>scopeName</key>
    <string>source.ftl</string>
    <key>fileTypes</key>
    <array>
      <string>ftl</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#syntax</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>syntax</key>
      <dict>
        <key>name</key>
        <string>meta.syntax.ftl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#term</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#message</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#pattern</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment-line</string>
          </dict>
        </array>
      </dict>
      <key>comment-line</key>
      <dict>
        <key>comment</key>
        <string>A comment is allowed anywhere outside a &lt;terminal string&gt;, &lt;meta identifier&gt;, &lt;integer&gt; or &lt;special sequence&gt;</string>
        <key>name</key>
        <string>comment.line.number-sign.ftl</string>
        <key>begin</key>
        <string>\#</string>
        <key>end</key>
        <string>\n</string>
      </dict>
      <key>term</key>
      <dict>
        <key>name</key>
        <string>meta.term.ftl</string>
        <key>begin</key>
        <string>^(?:\-)((?:[a-zA-Z])(?:[a-zA-Z0-9_-]*))(?:\s*?)(\={1})(?:\s*?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.ftl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ftl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>
</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
        </array>
      </dict>
      <key>text</key>
      <dict>
        <key>name</key>
        <string>string.unqouted.ftl</string>
        <key>match</key>
        <string>[^{}]</string>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>string.unqouted.ftl</string>
        <key>match</key>
        <string>(?:[a-zA-Z])(?:[a-zA-Z0-9_-]*)</string>
      </dict>
      <key>variable</key>
      <dict>
        <key>name</key>
        <string>entity.other.attribute-name.ftl</string>
        <key>match</key>
        <string>\$((?:[a-zA-Z])(?:[a-zA-Z]*))</string>
      </dict>
      <key>constant</key>
      <dict>
        <key>name</key>
        <string>variable.other.constant.ftl</string>
        <key>match</key>
        <string>\-((?:[a-zA-Z])(?:[a-zA-Z]*))</string>
      </dict>
      <key>selector</key>
      <dict>
        <key>name</key>
        <string>meta.selector.ftl</string>
        <key>match</key>
        <string>(\*?)(:?\[{1})((?:[a-zA-Z0-9])(?:[a-zA-Z0-9]*))(:?\]{1})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.ftl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.ftl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.constant.ftl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.ftl</string>
          </dict>
        </dict>
      </dict>
      <key>function</key>
      <dict>
        <key>name</key>
        <string>support.function.ftl</string>
        <key>match</key>
        <string>((?:[A-Z])(?:[A-Z]*))(\({1})(.*)(\){1})</string>
        <key>captures</key>
        <dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.ftl</string>
          </dict>
        </dict>
      </dict>
      <key>arrow-operator</key>
      <dict>
        <key>name</key>
        <string>storage.type.function.arrow.ftl</string>
        <key>match</key>
        <string>\-\&gt;</string>
      </dict>
      <key>placeable</key>
      <dict>
        <key>name</key>
        <string>string.unqouted.ftl</string>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.ftl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.ftl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#arrow-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
        </array>
      </dict>
      <key>message</key>
      <dict>
        <key>name</key>
        <string>meta.message.ftl</string>
        <key>begin</key>
        <string>^((?:[a-zA-Z])(?:[a-zA-Z0-9_-]*))(?:\s*?)(\={1})(?:\s*?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.ftl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ftl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>
</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#text</string>
          </dict>
        </array>
      </dict>
      <key>pattern</key>
      <dict>
        <key>name</key>
        <string>meta.pattern.ftl</string>
        <key>begin</key>
        <string>(:?\ +)(:?\.{1})((?:[a-zA-Z])(?:[a-zA-Z0-9_-]*))(?:\s*?)(\={1})(?:\s*?)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.ftl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.ftl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.ftl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>
</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#text</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>